### ISSUE TITLE
Internal server error on docs page

### ISSUE THREAD

**Issue by matusf** [oxidecomputer/cli-old#291]
The docs url https://docs.oxide.computer/cli/manual returns 500. It works without the trailing `/manual` path.

```
curl 'https://docs.oxide.computer/cli/manual' 
<!DOCTYPE html><html lang="en"><head><meta charSet="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"/><title>Application Error!</title></head><body><main style="font-family:system-ui, sans-serif;padding:2rem"><h1 style="font-size:24px">Application Error</h1><pre style="padding:2rem;background:hsla(10, 50%, 50%, 0.1);color:red;overflow:auto">TypeError: Cannot read properties of undefined (reading &#x27;path&#x27;)
    at Object.meta3 (/var/task/api/index.js:32904:19)
    at Meta (/var/task/node_modules/@remix-run/react/dist/components.js:561:76)
    at d (/var/task/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:33:498)
    at bb (/var/task/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:16)
    at a.b.render (/var/task/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:43)
    at a.b.read (/var/task/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
    at exports.renderToString (/var/task/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:52:138)
    at handleRequest (/var/task/api/index.js:60:49)
    at handleDocumentRequest (/var/task/node_modules/@remix-run/server-runtime/dist/server.js:395:18)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)</pre></main><script>
              console.log(
                "💿 Hey developer👋. You can provide a way better UX than this when your app throws errors. Check out https://remix.run/guides/errors for more information."
              );
            </script></body></html>
```

**Comment by karencfv** [comment]
Hey there, looks like it was a broken link. Thanks for the heads up! I've updated it

**Comment by david-crespo** [comment]
We should still 404 instead of 500. I’ll make an issue in the docs repo.
